### ISSUE TITLE
packages are not generated.

### ISSUE THREAD

**Issue by JocoNagy** [expretio/capnp-maven-plugin#2]
The plugin does not generate packages for the classes so they end up in the default package -outputDirectory/ instead of outputDirectory/packages/ -

**Comment by mtetreau** [comment]
Is the package annotation declared in your schema?

example: $Java.package("org.expretio.one");

**Comment by JocoNagy** [comment]
Yes it is declared and the generated class contains it as well.

**Comment by JocoNagy** [comment]
So basically the classes generated with the right package definition but they are actually not in those packages which causes compile error. The only configuration i use for the plugin is schemaDirectory.

**Comment by mtetreau** [comment]
Can you provide an example schema on which the problem occurs?

**Comment by JocoNagy** [comment]
**Plugin**:
```
            <plugin>
                <groupId>org.expretio.maven.plugins</groupId>
                <artifactId>capnp-maven-plugin</artifactId>
                <version>1.0</version>
                <configuration>
                    <schemaDirectory>src/main/resources/schema</schemaDirectory>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
**Schema**:
```
@0xabf8f53c554fa923;

using Java = import "java.capnp";
$Java.package("plugin.issue.example");
$Java.outerClassname("IssueClass");

struct Issue {
    text @0 : Text;
}
```
**The generated java class**:
```
package plugin.issue.example;

public final class IssueClass {
  public static class Issue {
      ...
  }
  ...
}
```
**The java class can be found under generated-sources\capnp**

**Comment by mtetreau** [comment]
Generated java files follows the path of given schema file from base directory. In your example, the schema must be located at: src/main/resources/schema/plugin/issue/example/file.capnp.

**Comment by JocoNagy** [comment]
I was missing this info. Works well.
Thanks!

**Comment by mtetreau** [comment]
No problem. 
I edited the example of the readme file in order to make it clearer.
